### ISSUE TITLE
Intel MacOS Sonoma14.0.0 在根目录yarn install 后报错SyntaxError: Unexpected token '.'

### ISSUE THREAD

**Issue by xiachonga** [xiaolai/everyone-can-use-english#143]
无论是直接git clone还是下载release版本的程序在执行yarn后都会出现相同的问题
SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:1053:16)
    at Module._compile (internal/modules/cjs/loader.js:1101:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)

**Comment by WuzenLiz** [comment]
What node version are you using? 
Mine using lts/Hydrogen. Everything work without error

**Comment by kyleliwotian** [comment]
node version is not the new one

**Comment by watonyweng** [comment]
Hi @xiachonga, you can execute the `npx envinfo` command in the root directory of the project.

**Comment by kyleliwotian** [comment]
nvm install --lts      install the last new versio
