### ISSUE TITLE
Enjoy客户端音频转文本时报错：Error: spawn UNKNOWN

### ISSUE THREAD

**Issue by allen2peace** [xiaolai/everyone-can-use-english#570]
大家好，我克隆了 Enjoy 项目源码，使用 `yarn install` 安装了依赖（都安装成功了，没有报错），然后使用 `yarn enjoy:start` 启动了程序，在我添加音频文件转文本的时候报了下面的错误：

> 10:18:17.807 (echogarden)                         > Error: spawn UNKNOWN
    at ChildProcess.spawn (node:internal/child_process:421:11)
    at spawn (node:child_process:776:9)
    at file:///F:/work/MyApp/Website/everyone-can-use-english/enjoy/node_modules/echogarden/dist/codecs/FFMpegTranscoder.js:36:25
    at new Promise (<anonymous>)
    at transcode_CLI (file:///F:/work/MyApp/Website/everyone-can-use-english/enjoy/node_modules/echogarden/dist/codecs/FFMpegTranscoder.js:32:12)
    at transcode (file:///F:/work/MyApp/Website/everyone-can-use-english/enjoy/node_modules/echogarden/dist/codecs/FFMpegTranscoder.js:29:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Module.decodeToChannels (file:///F:/work/MyApp/Website/everyone-can-use-english/enjoy/node_modules/echogarden/dist/codecs/FFMpegTranscoder.js:20:23)
    at async EchogardenWrapper.ensureRawAudio (file:///F:/work/MyApp/Website/everyone-can-use-english/enjoy/node_modules/echogarden/dist/audio/AudioUtilities.js:242:27)
    at async EchogardenWrapper.transcode (file:///F:/work/MyApp/Website/everyone-can-use-english/enjoy/.vite/build/main-DdL_IA8F.js:6680:22)
Error occurred in handler for 'echogarden-transcode': Error: spawn UNKNOWN
    at ChildProcess.spawn (node:internal/child_process:421:11)
    at spawn (node:child_process:776:9)
    at file:///F:/work/MyApp/Website/everyone-can-use-english/enjoy/node_modules/echogarden/dist/codecs/FFMpegTranscoder.js:36:25
    at new Promise (<anonymous>)
    at transcode_CLI (file:///F:/work/MyApp/Website/everyone-can-use-english/enjoy/node_modules/echogarden/dist/codecs/FFMpegTranscoder.js:32:12)
    at transcode (file:///F:/work/MyApp/Website/everyone-can-use-english/enjoy/node_modules/echogarden/dist/codecs/FFMpegTranscoder.js:29:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Module.decodeToChannels (file:///F:/work/MyApp/Website/everyone-can-use-english/enjoy/node_modules/echogarden/dist/codecs/FFMpegTranscoder.js:20:23)
    at async EchogardenWrapper.ensureRawAudio (file:///F:/work/MyApp/Website/everyone-can-use-english/enjoy/node_modules/echogarden/dist/audio/AudioUtilities.js:242:27)
    at async EchogardenWrapper.transcode (file:///F:/work/MyApp/Website/everyone-can-use-english/enjoy/.vite/build/main-DdL_IA8F.js:6680:22) {
  errno: -4094,
  code: 'UNKNOWN',
  syscall: 'spawn'
}

![Dingtalk_20240427104321](https://github.com/xiaolai/everyone-can-use-english/assets/6928331/bdde5463-2f34-4f46-8998-6e201484269c)

请问下这个是什么原因呢？

**Comment by an-lee** [comment]
看起来像是 ffmpeg 依赖没有安装成功，检查一下 `enjoy/node_modules/ffmpeg-static/ffmpeg` 文件是否存在，如果存在，可以用命令行测试一下这个文件是否能运行

```bash
./enjoy/node_modules/ffmpeg-static/ffmpeg -h
```

**Comment by allen2peace** [comment]
我运行这个命令之后提示「此应用无法在你的电脑上运行」的错误，搜了下可能是ffmpeg版本下载的不对，我删除重新使用 `yarn install`安装了一遍，现在可以了，感谢。
